//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letgo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veritabanım1Entities : DbContext
    {
        public veritabanım1Entities()
            : base("name=veritabanım1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblfavori> tblfavori { get; set; }
        public virtual DbSet<tblharita> tblharita { get; set; }
        public virtual DbSet<tblkategori> tblkategori { get; set; }
        public virtual DbSet<tblkullanıcı> tblkullanıcı { get; set; }
        public virtual DbSet<tblmesajkutusu> tblmesajkutusu { get; set; }
        public virtual DbSet<tblsatınal> tblsatınal { get; set; }
        public virtual DbSet<tblsatınaltalep> tblsatınaltalep { get; set; }
        public virtual DbSet<tblurun> tblurun { get; set; }
    }
}
