//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblharita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblharita()
        {
            this.tblkullanıcı = new HashSet<tblkullanıcı>();
            this.tblurun = new HashSet<tblurun>();
        }
    
        public int adresID { get; set; }
        public string adres { get; set; }
        public string x { get; set; }
        public string y { get; set; }
        public string acıklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblkullanıcı> tblkullanıcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblurun> tblurun { get; set; }
    }
}
