//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkullanıcı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblkullanıcı()
        {
            this.tblfavori = new HashSet<tblfavori>();
            this.tblmesajkutusu = new HashSet<tblmesajkutusu>();
            this.tblsatınal = new HashSet<tblsatınal>();
            this.tblsatınaltalep = new HashSet<tblsatınaltalep>();
            this.tblurun = new HashSet<tblurun>();
        }
    
        public int kullanııcID { get; set; }
        public string kullanıcıAdSoyad { get; set; }
        public string email { get; set; }
        public Nullable<int> password { get; set; }
        public Nullable<int> kullanıcıLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfavori> tblfavori { get; set; }
        public virtual tblharita tblharita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblmesajkutusu> tblmesajkutusu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatınal> tblsatınal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatınaltalep> tblsatınaltalep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblurun> tblurun { get; set; }
    }
}
