//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmesajkutusu
    {
        public int mesajID { get; set; }
        public Nullable<int> kullanıcıID { get; set; }
        public Nullable<int> atılıcakkisiID { get; set; }
        public string mesajicerik { get; set; }
        public Nullable<int> okundubilgisi { get; set; }
    
        public virtual tblkullanıcı tblkullanıcı { get; set; }
    }
}
