//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Letgo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblurun()
        {
            this.tblfavori = new HashSet<tblfavori>();
            this.tblsatınal = new HashSet<tblsatınal>();
            this.tblsatınaltalep = new HashSet<tblsatınaltalep>();
        }
    
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public Nullable<int> urunFiyat { get; set; }
        public string urunAcıklama { get; set; }
        public Nullable<System.DateTime> eklemeTarihi { get; set; }
        public Nullable<int> satıldıDurumu { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<int> kullanıcıID { get; set; }
        public Nullable<int> urunLocation { get; set; }
        public string urunfotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblfavori> tblfavori { get; set; }
        public virtual tblharita tblharita { get; set; }
        public virtual tblkategori tblkategori { get; set; }
        public virtual tblkullanıcı tblkullanıcı { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatınal> tblsatınal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatınaltalep> tblsatınaltalep { get; set; }
    }
}
